---
- hosts: Test_Server
  become: true
  become_user: root
  tasks:
  - name: stopping al running containers
    shell: docker stop $(docker ps -a -q)
	ignore_errors: true
  - name: Removing all unused containers
    command: docker system prune -fa